site_name: 'CTXCloudApi'
site_description: 'Documentation for PowerShell Module: CTXCloudApi'
site_author: 'Pierre Smit'
site_url: 'https://smitpi.github.io/CTXCloudApi'
 
repo_url: 'https://github.com/smitpi/CTXCloudApi'
repo_name:  'smitpi/CTXCloudApi'
 
copyright: '(c) 2021 Pierre Smit. All rights reserved.'
 
extra:
  manifest: manifest.webmanifest
  social:
    - icon: fontawesome/brands/github-square
      link: 'https://smitpi.github.io/CTXCloudApi'
 
markdown_extensions:
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.superfences
 
theme: material
